### ISSUE TITLE
A new UI for the Rajpath Recalls web app

### ISSUE THREAD

**Issue by emanuelchristo** [rajpathrecalls/rajpathrecalls.github.io#1]
I have made a somewhat functional new frontend for the Rajpath Recalls web app. However I can't figure out how to integrate the player, chat and calendar. I've looked at the js file, but it's so dense and complex. Can you help with integrating it into my frontend.

**This is the repo** 
[rajpath-recalls](https://github.com/emanuelchristo/rajpath-recalls)
It's made using svelte.

**Here's a demo** 
[Static version of the app](https://rajpath-recalls.herokuapp.com/)

**Comment by rajpathrecalls** [comment]
Thanks for the contribution to RR. UI looks amazing. Where can we contact you?

**Comment by emanuelchristo** [comment]
emanuelchristochris@gmail.com Contact me via email I'll give you my whatsapp no. or something...
